name: update-role
on:
  schedule:
    - cron:  '5 5,17 * * *'
  workflow_dispatch:

jobs:
  update-role:
    name: Update Role
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('update-role.py') }}-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt
      - name: "Update role"
        run: python update-role.py
        env:
          GUILD_ID: ${{ secrets.GUILD_ID }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          ADMIN_BOT_TOKEN: ${{ secrets.ADMIN_BOT_TOKEN }}
          HCPING_ID: ${{ secrets.HCPING_ID }}
